# Generated by Django 4.2.5 on 2023-09-10 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите класс автомобиля', max_length=50, verbose_name='Класс автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите статус автомобиля', max_length=20, verbose_name='Статус автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='CarUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carmodel', models.CharField(help_text='Введите модель автомобиля', max_length=50, verbose_name='Модель автомобиля')),
                ('summary', models.TextField(help_text='Введите краткие сведения об автомобиле', max_length=1000)),
                ('winnum', models.CharField(help_text='Должно содержать 17 символов', max_length=17, verbose_name='WIN номер')),
                ('carclass', models.ForeignKey(help_text='Выберите класс автомобиля', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.carclass', verbose_name='Класс автомобиля')),
            ],
        ),
        migrations.CreateModel(
            name='CarInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('govnum', models.CharField(help_text='Введите гос номер', max_length=9, null=True, verbose_name='Госномер')),
                ('due_back', models.DateField(blank=True, help_text='Введите конец срока статуса', null=True, verbose_name='Дата окончания статуса')),
                ('carunit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.carunit')),
                ('status', models.ForeignKey(help_text='Изменить статус автомобиля', null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.status', verbose_name='Статус автомобиля')),
            ],
        ),
    ]
